### ISSUE TITLE
Придумать протокол для передачи различных пакетов

### ISSUE THREAD

**Issue by Kaffeine** [UrFU-Programming/IsitMessenger#20]
Типы пакетов:
1. Сообщение от клиента другим клиентам
2. Попытка клиента выбрать nickname
3. Ответ сервера о выборе nickname

**Comment by i-ka** [comment]
1. m:<сообщение>
2. setNickname:<новый ник>
3. nickNameStatus: "0" если ник не принят, "1" если ник установлен

**Comment by Kaffeine** [comment]
https://github.com/UrFU-Programming/IsitMessenger/wiki/Protocol

@UrFU-Programming/z-team
